### ISSUE TITLE
View seed before playing

### ISSUE THREAD

**Issue by adamosimpson21** [dashrando/dash-rando-app#2]
Howdy! I would like a way to view the seed before completing the game. Is there a way to do this while still maintaining race integrity? Could it possibly be a setting when creating a seed? Love the randomizer and its been super fun to play.

**Comment by dashrando** [comment]
Glad you are enjoying the randomizer! The code can be built to show all of the locations in a log file, but we currently don't leave that feature enabled on the versions we release. We use that feature a bunch for generating statistics. We'll think about adding a way to turn that on (command argument or something), but until then you could always pull and build the code yourself and pass along a true to MainForm for the GenerateSpoiler argument within the "Program.cs" file.
